tunnel: 038b9d74-1d85-4cbf-89bd-118383b06364
credentials-file: /Users/itopa/.cloudflared/038b9d74-1d85-4cbf-89bd-118383b06364.json

ingress:
  # Frontend application - Studio UI
  - hostname: studio.confamd.com
    service: http://localhost:3000
  # Catch-all rule
  - service: http_status:404
